version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: academic_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: academic_pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
