# docker-compose.yml
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: academic_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  backend:
    build: ./backend
    container_name: academic_backend
    env_file:
      - .env
    depends_on:
      - postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: academic_pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: